export const patientFormConfig = [
  {
    name: "patientId",
    label: "Patient ID",
    type: "text",
    placeholder: "Enter Patient ID",
    required: true,
  },
  {
    name: "name",
    label: "Name",
    type: "text",
    placeholder: "Enter full name",
    required: true,
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    placeholder: "Enter email address",
    required: true,
  },
  {
    name: "mobileString",
    label: "Mobile Number",
    type: "tel",
    placeholder: "Enter mobile number",
    required: true,
  },
  {
    name: "address",
    label: "Address",
    type: "textarea",
    placeholder: "Enter address",
    required: true,
  },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    options: ["Male", "Female", "Other"],
    required: true,
  },
  {
    name: "dob",
    label: "Date of Birth",
    type: "date",
    required: true,
  },
  {
    name: "medicalIssues",
    label: "Medical Issues",
    type: "textarea",
    placeholder: "Enter any existing medical issues",
    required: false,
  },
  {
    name: "bloodGroup",
    label: "Blood Group",
    type: "select",
    options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
    required: true,
  },
  {
    name: "patientType",
    label: "Patient Type",
    type: "select",
    options: ["OPD", "IPD", "Emergency"],
    required: true,
    showInForm: true,
    showInTable: true,
  },
  {
    name: "assignedDoctor",
    label: "Assigned Doctor",
    type: "text",
    placeholder: "Enter doctor name",
    required: false,
    showInForm: false,
    showInTable: true,
  },
];
