export const userManagementConfig = [
  {
    name: "userId",
    label: "User ID",
    type: "text",
    placeholder: "Enter User ID",
    required: true,
    showInForm: false,
    showInTable: true,
  },
  {
    name: "name",
    label: "Name",
    type: "text",
    placeholder: "Enter Name",
    required: true,
    showInForm: true,
    showInTable: true,
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    placeholder: "Enter Email",
    required: true,
    showInForm: true,
    showInTable: true,
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    placeholder: "Enter Password",
    required: true,
    showInForm: true,
    showInTable: true,
    render: () => "*******",
  },
  {
    name: "role",
    label: "Role",
    type: "select",
    placeholder: "Select Role",
    required: true,
    showInForm: true,
    showInTable: true,
  },
  {
    name: "lastLogin",
    label: "Last Login",
    type: "date",
    placeholder: "Last Login Date",
    required: false,
    showInForm: false,
    showInTable: true,
  },
];
